#!/usr/bin/env bash
# Author:       Jon Smithers <mail@jonsmithers.link>
# Last Updated: 2019-09-22
# URL:          https://github.com/jonsmithers/dotfiles/blob/master/git/git-website
# Description:  Opens the webpage for the current git repo.

# The website url is obtained by manipulating the git remote url of the current
# repo. Examples:
#
#   | GIT REMOTE URL                                   | BROWSER URL                                  |
#   | ------------------------------------------------ | -------------------------------------------- |
#   | git@website.com:some-author/name-of-repo.git     | https://website.com/some-author/name-of-repo |
#   | https://website.com/some-author/name-of-repo.git | https://website.com/some-author/name-of-repo |

url=$(git remote --verbose \
    | grep '^origin' \
    | grep fetch \
    | sed -E 's/origin.([^[:space:]]+)\.git.*/\1/' \
    | sed -E 's/git@/https:\/\//' \
    | sed -E 's/https:\/\/[a-zA-Z.]+@/https:\/\//' \
    | sed -E 's#^(https?:[^:]*):#\1/#'
    )
# echo "$url"
python -mwebbrowser -t "$url"
