#!/usr/bin/env bash
# Author:       Jon Smithers <mail@jonsmithers.link>
# Last Updated: 2019-03-14
# URL:          https://github.com/jonsmithers/dotfiles/blob/master/git/git-website

url=$(git remote --verbose \
    | grep '^origin' \
    | grep fetch \
    | sed -E 's/origin.([^[:space:]]+)\.git.*/\1/' \
    | sed -E 's/git@/https:\/\//' \
    | sed -E 's/https:\/\/[a-zA-Z.]+@/https:\/\//' \
    | sed -E 's/com:/com\//'
    )
# echo $url
python -mwebbrowser -t $url
