#! /usr/bin/env bash
# Author:       Jon Smithers <mail@jonsmithers.link>
# Last Updated: 2019-09-27
# URL:          https://github.com/jonsmithers/dotfiles/blob/master/git/git-tracker

RED='\033[0;31m'
YELLOW='\033[1;33m'
NORMAL='\033[0m'
BOLD='\033[1m'

arg="$1"

if [[ "$arg" = "--help" ]] || [[ "$arg" = "help" ]]; then
  cat <<- END
git-tracker

NAME
        git-tracker - open browser to tracker id mentioned in commit
SYNOPSIS
        git tracker [<refspec>]
END
  exit 0
fi

if [[ -z "$PIVOTAL_TRACKER_PROJECT" ]]; then
  echo -e "$RED""Missing $BOLD\$PIVOTAL_TRACKER_PROJECT$NORMAL$RED environment variable""$NORMAL"
  exit 1
fi

if [[ -z "$1" ]]; then
  arg=HEAD
fi
if [[ "$1" =~ ^#?[0-9]{8}$ ]]; then
  echo specifiyng tracker id directly is not implemented
  exit 1
else
  if ! commit_sha=$(git rev-parse $arg 2> /dev/null); then
    echo "error getting commit sha for \"$arg\""
    exit 1
  fi
  story_id=$(git show "$commit_sha" | grep -e '#[[:digit:]]\{9\}' --only-matching)
  if [[ -z "$story_id" ]]; then
    echo -e "$YELLOW""Story id not found in commit $commit_sha""$NORMAL"
    exit 1
  fi
fi

if [[ $(command -v open) ]]; then
  open_cmd=open
else
  open_cmd=xdg-open
fi

$open_cmd "https://www.pivotaltracker.com/n/projects/$PIVOTAL_TRACKER_PROJECT/stories/${story_id//\#/}"
