#!/bin/bash
source _helpers.sh
if prompt "Symlink dotfiles?"; then
  ./dotphile
fi

if grep --quiet github.com < ~/.ssh/config; then
  echo -e " ${GREEN}✓${NORMAL} github key present"
elif prompt " ${RED}✗${NORMAL} missing github key - create?"; then
  set -eoux pipefail
  ssh-keygen -t ed25519 -C "jon@smithers.dev" -f "$HOME/.ssh/github"
  pbcopy < ~/.ssh/github.pub
  eval "$(ssh-agent -s)"

  (
    set +x
    echo
    echo Key has been copied to clipboard. Add this key to github
    read -p "(press enter) " -n 1 -r || exit 1; echo
  )
  open https://github.com/settings/keys

  touch ~/.ssh/config
  tee -a ~/.ssh/config <<END
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/github
END
fi

if [[ -f './hammerspoon/Spoons/hs_select_window.spoon/.git' ]]; then
  echo -e " ${GREEN}✓${NORMAL} git submodule present"
elif prompt " ${RED}✗${NORMAL} missing git submodule - clone?"; then
  (
    set -ex
    git submodule update --recursive --remote
  )
fi

if [[ $(command -v fzf) ]]; then
  echo -e " ${GREEN}✓${NORMAL} fzf installed"
elif prompt " ${RED}✗${NORMAL} missing fzf - install?"; then
  [[ -d "$HOME/.fzf" ]] && echo_and_run rm -rf "$HOME/.fzf"
  echo_and_run git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  echo_and_run ~/.fzf/install --all
fi

function install_cmd() {
  local dnf=''
  local brew=''
  local apt=''
  local linux=''
  local not=''
  local cmd="$1"; shift;
  while :; do
    case $1 in
      --dnf)
        if [[ "$2" ]]; then
          dnf="$2"
          shift
        else
          echo "missing dnf value"
          exit 1
        fi
        ;;
      --not=?*)
        not="${1#*=}"; shift;
        ;;
      --linux=?*)
        linux="${1#*=}"; shift;
        ;;
      --brew=?*)
        brew="${1#*=}"; shift;
        ;;
      --dnf=?*)
        dnf="${1#*=}"; shift;
        ;;
      --apt=?*)
        apt="${1#*=}"; shift;
        ;;
      ?*)
        echo "unknown option \"$1\""
        exit 1
        ;;
      *)
        break;
    esac
  done
  if [[ $(command -v "$cmd") && "$(command -v "$cmd")" != "$not" ]]; then
    echo -e " ${GREEN}✓${NORMAL} $cmd installed"
  elif prompt " ${RED}✗${NORMAL} missing $cmd - install?"; then
    if [[ -n "$linux" && "$(uname -s)" == "Linux" ]]; then
      eval "echo_and_run $linux"
    elif [[ $(command -v brew) ]]; then
      if [[ -n "$brew" ]]; then
        eval "echo_and_run $brew"
      else
        echo_and_run brew install "$cmd"
      fi
    elif [[ $(command -v dnf) ]]; then
      if [[ -n "$dnf" ]]; then
        eval "echo_and_run $dnf"
      else
        echo_and_run sudo dnf install --assumeyes "$cmd"
      fi
    elif [[ $(command -v apt) ]]; then
      if [[ -n "$apt" ]]; then
        eval "echo_and_run $apt"
      else
        echo_and_run sudo apt install "$cmd"
      fi
    else
      echo "I don't know how to install this"
      exit 1
    fi
  fi
}

function install_git_number_on_linux() {
  echo_and_run mkdir -p ~/git/git-number
  echo_and_run git clone https://github.com/holygeek/git-number.git ~/git/git-number
  (
    cd ~/git/git-number || exit 1;
    echo_and_run sudo make install;
  );
}

install_cmd zsh --not="/bin/zsh"
install_cmd rg --brew="brew install ripgrep" --dnf="sudo dnf install --assumeyes ripgrep"
install_cmd git-number --linux="install_git_number_on_linux"
install_cmd alacritty
install_cmd bat
install_cmd delta --brew="brew install git-delta" --dnf="sudo dnf install --assumeyes git-delta"
install_cmd lsd
install_cmd node
install_cmd kitty --brew="curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin" --dnf="curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin" --apt="curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin"
install_cmd direnv
install_cmd zoxide
# install_cmd fish
# install_cmd shellcheck --dnf="sudo dnf install --assumeyes ShellCheck"
# install_cmd tmux
# install_cmd vint # vimscript linting
zsh/setup-zsh.sh
if [[ "$(uname)" == "Darwin" ]] && prompt "Set MacOS defaults?"; then
  osx/set-defaults.sh
fi
