#!/bin/bash
source _helpers.sh
if prompt "Symlink dotfiles?"; then
  if [[ $(python --version 2>&1) =~ ^Python\ 3\. ]]; then
    ./dotphile3
  else
    ./dotphile
  fi
fi

if [[ $(command -v fzf) ]]; then
  echo -e " ${GREEN}✓${NORMAL} fzf installed"
elif prompt " ${RED}✗${NORMAL} missing fzf - install?"; then
  [[ -d "$HOME/.fzf" ]] && echo_and_run rm -rf "$HOME/.fzf"
  echo_and_run git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  echo_and_run ~/.fzf/install --all
fi

function install_cmd() {
  local dnf=''
  local brew=''
  local apt=''
  local linux=''
  local cmd="$1"; shift;
  while :; do
    case $1 in
      --dnf)
        if [[ "$2" ]]; then
          dnf="$2"
          shift
        else
          echo "missing dnf value"
          exit 1
        fi
        ;;
      --dnf=?*)
        dnf="${1#*=}"; shift;
        ;;
      --brew=?*)
        brew="${1#*=}"; shift;
        ;;
      --apt=?*)
        apt="${1#*=}"; shift;
        ;;
      --linux=?*)
        linux="${1#*=}"; shift;
        ;;
      ?*)
        echo "unknown option \"$1\""
        exit 1
        ;;
      *)
        break;
    esac
  done
  if [[ $(command -v "$cmd") ]]; then
    echo -e " ${GREEN}✓${NORMAL} "$cmd" installed"
  elif prompt " ${RED}✗${NORMAL} missing "$cmd" - install?"; then
    if [[ -n "$linux" &&  "$(uname)" == "Darwin" ]]; then
      eval "echo_and_run $linux"
    elif [[ $(command -v brew) ]]; then
      if [[ -n "$brew" ]]; then
        eval "echo_and_run $brew"
      else
        echo_and_run brew install "$cmd"
      fi
    elif [[ $(command -v dnf) ]]; then
      if [[ -n "$dnf" ]]; then
        eval "echo_and_run $dnf"
      else
        echo_and_run sudo dnf install "$cmd"
      fi
    elif [[ $(command -v apt) ]]; then
      if [[ -n "$apt" ]]; then
        eval "echo_and_run $apt"
      else
        echo_and_run sudo apt install "$cmd"
      fi
    else
      echo "I don't know how to install this"
      exit 1
    fi
  fi
}

function linux_git_number() {
  echo_and_run mkdir -p ~/git/git-number
  echo_and_run git clone https://github.com/holygeek/git-number.git ~/git/git-number
  (
    cd ~/git/git-number;
    echo_and_run sudo make install;
  );
}

install_cmd zsh
install_cmd rg --brew="brew install ripgrep" --dnf="sudo dnf install ripgrep"
install_cmd git-number --linux="linux_git_number"
install_cmd tmux
install_cmd autojump
install_cmd alacritty
install_cmd node
install_cmd shellcheck --dnf="sudo dnf install ShellCheck"
install_cmd fish
install_cmd vint # vimscript linting

vim/setup-vim.sh
zsh/setup-zsh.sh
osx/set-defaults.sh
