" allegedly necessary for cool vim things
set nocompatible

" Misc basics
  set ttimeoutlen=0 "timeout instantly when pressing esc during visual mode
  set foldmethod=indent
  set foldlevelstart=20
  set nowrap
  syntax on
  set number
  set autoindent
  set smartindent
  set showcmd	  " show more info about what you're doing

" Tabs
  set expandtab     " spaces are better than tab characters
  set smarttab      " don't know
  set tabstop=2     " for when you press tab
  set shiftwidth=2  " for autoindent, I think
  func! SetTabSizeFour()
    set tabstop=4
    set shiftwidth=4
  endfu
  com! Tab4 call SetTabSizeFour()

" Prose
  set nojoinspaces
  func! WriteMode()
    set fo=ant
    set flp=^\\s*\\(-\\\\|\\d\\+\\.\\)\\s*
        "formtlistpat=^\s*\(-\|\d\+\.\)\s*
    set formatprg=par\ -jw80
    set nosmartindent
    set foldmethod=indent
    " ^ this only affects gqip, NOTHING ELSE
    " see [help gq]
    set whichwrap+=h,l
  endfu
  com! WM call WriteMode()
  func! NoWriteMode()
    set fo=croql
    set flp=^\s*\d\+[\]:.)}\t ]\s*
    "set formatprg
    "set smartindent
    set foldmethod=indent
    set whichwrap=b,s
  endfu
  com! WMoff call NoWriteMode()

  "I don't use the below function because scrolling is really funky. A
  "paragraph is either all-visible or all-hidden. Nothing in between.
  func! SoftWrappedProcessorMode()
    setlocal noexpandtab
    setlocal wrap
    setlocal linebreak
    setlocal breakindent
    map j gj
    map k gk
    set formatprg=par -jw80
    "setlocal spell spelllang=en_us
    "set thesaurus+=/Users/sbrown/.vim/thesaurus/mthesaur.txt
    "set complete+=s
  endfu
com! SoftWrapProcessor call SoftWrappedProcessorMode()

" Wrap gitcommit file types at the appropriate length
  " filetype indent plugin on
  " filetype on

"# GUI customization
  if has('gui_running')
    syntax enable
    set background=dark
    colorscheme solarized
    set gfn=Fira\ Mono\ Medium\ for\ Powerline\ Medium\ 10,\ Monaco\ for\ Powerline:h14
    set autoread

    :set guioptions-=m  "remove menu bar
    :set guioptions-=T  "remove toolbar
    :set guioptions-=r  "remove right-hand scroll bar
    :set guioptions-=L  "remove left-hand scroll bar
    :set go+=m " I think I want to keep the menu actually
  endif

" Highlighting overlength
  " highlight OverLength ctermbg=red ctermfg=white guibg=#592929
  " match OverLength /\%81v.\+/

" Macros
  " lazy initialization
    let @l="yiwiif (jjA == null) {^M}jja else {^Mreturn jjpa;^M}jjkk"
  " vimscript to toggle syntax highlighting
    function! ToggleSyntax()
       if exists("g:syntax_on")
          syntax off
       else
          syntax enable
       endif
    endfunction

"# Keyboard keys
  " insert mode shortcuts
  :imap <C-@> <C-Space>
  :imap <C-Space> <C-x><C-o>
  :imap jk 
  :inoremap II <Esc>I
  :inoremap AA <Esc>A
  :inoremap jl <Esc>:
  :imap \t <Esc>:r! date "+\%Y\%m\%d"<Enter>kJA

  " normal mode shortucts
  :nnoremap \	 :e#
  :nmap \t :r! date "+\%Y\%m\%d"<Enter>kJ
  :nmap  zh
  :nmap  zl


" wrap overlength text
  :nmap <leader>w 080lF<Space>a
  " auto-resize a window to 80+4 cols
  :nmap <leader>Width :vertical resize 84

" Pasting
  "The first line sets a mapping so that pressing \p in normal mode will invert
  "the 'paste' option, and will then show the value of that option. The second
  "line allows you to press \\ppp when in insert mode, to toggle 'paste' on and
  "off. The third line enables displaying whether 'paste' is turned on in
  "insert mode.
  "source: http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
  :nnoremap \p :set invpaste paste?<CR>
  :set pastetoggle=\\ppp
  :set showmode

call plug#begin('~/.vim/plugged')
Plug 'junegunn/goyo.vim'
Plug 'fatih/vim-go'
Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'scrooloose/syntastic'
Plug 'ternjs/tern_for_vim'
call plug#end()
" run :PlugInstall to install new plugins

" SYNTASTIC PLUGIN config
let g:syntastic_html_checkers = []
let g:syntastic_javascript_checkers = ['jshint']

" CTRLP PLUGIN config
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll|class)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:ctrlp_by_filename = 1

" GOYO PLUGIN config
" make vim close the First time you do :quit
" https://github.com/junegunn/goyo.vim/wiki/Customization
function! s:goyo_enter()
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
endfunction
function! s:goyo_leave()
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif
endfunction
autocmd User GoyoEnter call <SID>goyo_enter()
autocmd User GoyoLeave call <SID>goyo_leave()

filetype off                 " vundle required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
call vundle#end()            " vundle required
filetype plugin indent on    " vundle required

"for airline
set laststatus=2     "always show airline, instead of only after splitview
let g:airline_powerline_fonts = 1
set t_Co=256 "needed for airline to show colors
