" VIM PLUG
  call plug#begin('~/.vim/plugged')
    Plug 'bling/vim-airline'
    Plug 'Shougo/deoplete.nvim'
    Plug 'fatih/vim-go'
    Plug 'iamcco/markdown-preview.vim'
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'junegunn/fzf.vim'
    Plug 'junegunn/goyo.vim'       " distraction-free mode
    Plug 'junegunn/vim-easy-align'
    " Plug 'junegunn/vim-peekaboo'
    Plug 'mattn/emmet-vim'
    Plug 'pangloss/vim-javascript'
    Plug 'scrooloose/nerdtree'
    Plug 'scrooloose/syntastic'
    Plug 'ternjs/tern_for_vim', { 'do': 'npm install' }
    Plug 'tomtom/tcomment_vim'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-rhubarb'
    Plug 'SirVer/ultisnips'

    " colorschemes
    Plug 'mhartington/oceanic-next'
    Plug 'morhetz/gruvbox'
    Plug 'nanotech/jellybeans.vim'

    "run :PlugInstall to install new plugins
  call plug#end()

" AIRLINE PLUGIN config
  set laststatus=2                                 "always show airline, instead of only after splitview
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1     "show buffers on top
  let g:airline#extensions#tabline#fnamemod = ':t' "show just the filename
  let g:airline_theme='gruvbox'
  set t_Co=256                                     "help airline show colors

" DEOPLETE PLUGIN config
  com! Deoplete call deoplete#enable() " use this to start deoplete
  let g:deoplete#file#enable_buffer_path=1   "path completion is relative

  if (hostname() == "Smithers.local")
    let g:python3_host_prog='/usr/local/bin/python3'
  " elseif (hostname == "zamperini2")
  "   let g:python3_host_prog='/usr/bin/python3'
  endif

" GOYO PLUGIN config
  let g:goyo_width = 81
  " make vim close the First time you do :quit
  " https://github.com/junegunn/goyo.vim/wiki/Customization
  function! s:goyo_enter()
    let b:quitting = 0
    let b:quitting_bang = 0
    autocmd QuitPre <buffer> let b:quitting = 1
    cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
  endfunction
  function! s:goyo_leave()
    " Quit Vim if this is the only remaining buffer
    if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
      if b:quitting_bang
        qa!
      else
        qa
      endif
    endif
  endfunction
  autocmd User GoyoEnter call <SID>goyo_enter()
  autocmd User GoyoLeave call <SID>goyo_leave()

" MARKDOWN PLUGIN config
  let g:mkdp_path_to_chrome = "open -a Google\\ Chrome"

" VIM-JAVASCRIPT PLUGIN conifg
  let g:javascript_plugin_jsdoc = 1

" SYNTASTIC PLUGIN config
  let g:syntastic_html_checkers = ['jshint']
  let g:syntastic_javascript_checkers = ['jshint']

" ULTISNIPS PLUGIN config
  " workaround bug https://github.com/SirVer/ultisnips/issues/711
  let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']

" Key Bindings
  " insert mode shortcuts
    :imap <C-@> <C-Space>
    :imap <C-Space> <C-x><C-o>
    :imap jk 
    :inoremap II <Esc>I
    :inoremap AA <Esc>A
    :inoremap jl <Esc>:
    :imap \t <Esc>:r! date "+\%Y\%m\%d"<Enter>kJA
    :imap <c-x><c-f> <plug>(fzf-complete-file)

  " normal mode shortucts
    :let mapleader = " "
    "insert time:
    :nmap <Leader>it :r! date "+\%Y\%m\%d"<Enter>kJ
    "insert js log
    :nmap <Leader>il oconsole.log();F)i
    "insert js LOG:
    :nmap <Leader>iL oconsole.log('%c', 'font-size:15px');F,hi
    "insert jsdoc comment in html
    :nmap <Leader>ihjd O/****/kA 
    :nmap <C-h> 2zh
    :nmap <C-l> 2zl
    :nnoremap Q <nop>
    :nmap <Leader>T :enew<cr>
    :nmap <Leader>k :bnext
    :nmap <Leader>j :bprevious
    let g:BASH_Ctrl_j = 'off' "this is undocumented!
    :nmap <c-j> :bprevious
    :nmap <c-k> :bnext
    :nmap <Leader>x :NERDTreeClose<enter>:bd
    :nmap <Leader>X :bd!
    :nmap <Leader>w :NERDTreeClose<enter>:bd
    :nmap <Leader>W :bd!
    :nmap <Leader><Tab> :b#
          "most recent buffer

    "easy-align-vim stuff
    :xmap ga <Plug>(EasyAlign)
    :nmap ga <Plug>(EasyAlign)

    " fzf stuff
    :nmap  :Files
    :nmap <Leader>or :History
    " ^ open recent file
    :nmap <Leader>/ :History/
    :nmap <Leader><C-r> :History:
    " call histdel("cmd", "regexp") to delete mistaken history items
    :nmap <Leader>f~ :FZF ~


    " nerdtree stuff
    :nmap <Leader>tt :NERDTreeToggle
    :nmap <Leader>tf :NERDTreeFind

    " ternjs stuf
    :nmap <Leader>td :TernDoc<cr>
    :autocmd CompleteDone * pclose

  " terminal mode shortcuts
    if has('nvim')
      :tnoremap <C-w> <C-\><C-n><C-w>
    endif

" Prose
  set nojoinspaces  " prevent vim from inserting 2 spaces after periods.
  func! WriteMode()
    set fo=ant
    set flp=^\\s*\\(-\\\\|\\d\\+\\.\\)\\s*
        "formtlistpat=^\s*\(-\|\d\+\.\)\s*
    set formatprg=par\ -jw80
    set nosmartindent
    set foldmethod=indent
    " ^ this only affects gqip, NOTHING ELSE
    " see [help gq]
    set whichwrap+=h,l
    let g:deoplete#disable_auto_complete = 1
    set sidescrolloff=0
  endfu
  com! WM call WriteMode()
  func! NoWriteMode()
    set fo=croql
    " set flp=^\s*\d\+[\]:.)}\t ]\s*
    "set formatprg
    "set smartindent
    set foldmethod=indent
    set whichwrap=b,s
    let g:deoplete#disable_auto_complete = 0

    set sidescrolloff=5 " Show next 5 columns while side-scrolling.
  endfu
  com! WMoff call NoWriteMode()

  "I don't use the below function because scrolling is really funky. A
  "paragraph is either all-visible or all-hidden. Nothing in between.
  func! SoftWrappedProcessorMode()
    setlocal noexpandtab
    setlocal wrap
    setlocal linebreak
    setlocal breakindent
    map j gj
    map k gk
    set formatprg=par -jw80
    "setlocal spell spelllang=en_us
    "set thesaurus+=/Users/sbrown/.vim/thesaurus/mthesaur.txt
    "set complete+=s
  endfu
  com! SoftWrapProcessor call SoftWrappedProcessorMode()

" visor style terminal buffer
  " https://www.reddit.com/r/neovim/comments/3cu8fl/quick_visor_style_terminal_buffer/
  let s:termbuf = 0
  function! ToggleTerm()
      topleft 30 split
      try
          exe 'buffer' . s:termbuf
          startinsert
      catch
          terminal
          let s:termbuf=bufnr('%')
          tnoremap <buffer> <A-t>  <C-\><C-n>:close<cr>
      endtry
  endfunction
  com! ToggleTerm call ToggleTerm()
  nnoremap <A-t> :ToggleTerm<cr>


"# GUI Customization
  if has('gui_running')
    set background=dark
    set gfn=Fira\ Mono\ Medium\ for\ Powerline\ Medium\ 10,\ Monaco\ for\ Powerline:h14
    set autoread        "auto-load changes from disk

    :set guioptions-=m  "remove menu bar
    :set guioptions-=T  "remove toolbar
    :set guioptions-=r  "remove right-hand scroll bar
    :set guioptions-=L  "remove left-hand scroll bar
    :set go+=m " I think I want to keep the menu actually
  endif

" Rare Tools
  func! HighlightOverlength()
    highlight OverLength ctermbg=red ctermfg=white guibg=#592929
    match OverLength /\%81v.\+/
  endfu
  func! SetWidthEightyFour()
    :vertical resize 84
  endfu

" Basics
  set ttimeoutlen=0 "timeout instantly when pressing esc during visual mode
  set foldmethod=indent
  set foldlevelstart=20
  set nowrap
  set incsearch     "incremental search (something else also turns this on)
  set ignorecase    "search ignores case
  set smartcase     "unless there's a capital letter
  syntax enable
  set number
  set autoindent
  set smartindent

  set splitbelow    " more natural split behavior
  set splitright    " more natural split behavior

  set hidden        " leave buffers without saving

  if !&scrolloff
    set scrolloff=3 " Show next 3 lines while scrolling.
  endif
  if !&sidescrolloff
    set sidescrolloff=5 " Show next 5 columns while side-scrolling.
  endif
  "(source: http://nerditya.com/code/guide-to-neovim/)

" Tabs
  set expandtab     " spaces are better than tab characters
  set smarttab      " don't know
  func! SetTabSizeFour()
    set tabstop=4     " for when you press tab
    set shiftwidth=4  " for autoindent, I think
  endfu
  com! Tab4 call SetTabSizeFour()
  func! SetTabSizeTwo()
    set tabstop=2     " for when you press tab
    set shiftwidth=2  " for autoindent, I think
  endfu
  com! Tab2 call SetTabSizeTwo()
  if (hostname() == "Smithers.local")
    :Tab4
  elseif (hostname() == "zamperini2")
    :Tab2
  elseif (hostname() == "zamperini3")
    :Tab2
  endif
  func! JSFormatting()
    autocmd FileType javascript setlocal equalprg=js-beautify\ --stdin
  endfu

" Neovim specific
  if has('nvim')
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
    colorscheme gruvbox
    set background=dark
    set nofixeol      " don't insert EOL at end of file
    Deoplete
  end
