#!/bin/bash

# This script prompts for choice of theme and then configures vim and kitty to
# have matching themes.
#
# Additional Kitty Setup
# =======================
#
# None. This script will automatically obtain the necessary theme assets.
#
#
# Additional Vim Setup
# ====================
#
# 1. If the script doesn't see the theme plugins in your vimrc, it will
#    automatically download colorscheme plugins into vim's native plugin
#    directory:
#
#        git clone <theme-repo> ~/.vim/pack/<theme>/start/<theme>
#
# 2. Configure vimrc to read environment variables "$VIM_BACKGROUND" and
#    "$VIM_COLORSCHEME" and "$VIM_THEME_GLOBALS" like so:
#
#        if (!exists('g:colors_name')) " no colorscheme set
#          if exists('$VIM_BACKGROUND')
#            execute 'set background='..$VIM_BACKGROUND
#          endif
#          if exists('$VIM_COLORSCHEME')
#            execute 'silent! colorscheme '..$VIM_COLORSCHEME
#          endif
#          if exists('$VIM_THEME_GLOBALS')
#            for assignment in split($VIM_THEME_GLOBALS, ',')
#              sandbox execute 'let g:'..split(assignment, '=')[0]..'="'..split(assignment, '=')[1]..'"'
#            endfor
#            execute 'silent! colorscheme ' .. $VIM_COLORSCHEME
#          endif
#        endif

set -e -o pipefail

function change_vim_colorscheme() {
  local theme="$1"
  local globals="$2"
  echo setting vim theme to "$theme"
  local line_to_insert="export VIM_COLORSCHEME=$theme"
  if grep --quiet '^export VIM_COLORSCHEME' < ~/.zshenv; then
    sed -I '.sedbackup' 's/^export VIM_COLORSCHEME=.*/'"$line_to_insert"'/' ~/.zshenv
    rm ~/.zshenv.sedbackup
  else
    echo "$line_to_insert" >> ~/.zshenv
  fi
  line_to_insert="export VIM_THEME_GLOBALS='$globals'"
  if grep --quiet '^export VIM_THEME_GLOBALS' < ~/.zshenv; then
    sed -I '.sedbackup' 's/^export VIM_THEME_GLOBALS=.*/'"$line_to_insert"'/' ~/.zshenv
    rm ~/.zshenv.sedbackup
  else
    echo "$line_to_insert" >> ~/.zshenv
  fi
}
function change_vim_background() {
  local background=$1
  local line_to_insert="export VIM_BACKGROUND=$background"
  if grep --quiet '^export VIM_BACKGROUND' < ~/.zshenv; then
    sed -I '.sedbackup' 's/^export VIM_BACKGROUND=.*/'"$line_to_insert"'/' ~/.zshenv
    rm ~/.zshenv.sedbackup
  else
    echo "$line_to_insert" >> ~/.zshenv
  fi
}
function change_kitty_theme() {
  local theme=$1
  echo setting kitty theme to "$theme"
  [[ -f "$HOME/.config/kitty/profile.conf" ]] || touch ~/.config/kitty/profile.conf
  if ! grep --quiet "include profile.conf" < ~/.config/kitty/kitty.conf; then
    echo "include profile.conf" >> ~/.config/kitty/kitty.conf
  fi
  local sed_target
  sed_target="$(readlink ~/.config/kitty/profile.conf || echo ~/.config/kitty/profile.conf)"
  sed \
    -I '.sedbackup' \
    '/# begin auto-generated kitty theme setting/,/# end auto-generated kitty theme setting/s/^[^#].*$/include '"$theme"'.conf/' \
    "$sed_target"
  rm "${sed_target}.sedbackup"
  if ! grep --quiet "^include $theme.conf$" < "$sed_target"; then
    echo "adding auto-generated section to $sed_target"
    {
      echo '# begin auto-generated kitty theme setting'
      echo "include $theme.conf"
      echo '# end auto-generated kitty theme setting'
    } >> "$sed_target"
  fi
  [[ -f "$HOME/.config/kitty/$theme.conf" ]] || {
    echo This kitty theme does not exist! "$HOME/.config/kitty/$theme.conf"
  }
}
function obtain_neovim_theme_from_git() {
  local theme_plugin=$1
  local git_remote=$2
  if [[ -d "$HOME/.config/nvim/pack/$theme_plugin/start/$theme_plugin" ]]; then
    echo found "$theme_plugin" in ~/.config/nvim/pack/"$theme_plugin"/start
    return
  else
    echo obtaining neovim theme from git repo;
    git clone "$git_remote" "$HOME/.config/nvim/pack/$theme_plugin/start/$theme_plugin"
  fi
}
function obtain_kitty_theme_from_curl() {
  local theme=$1
  local curl_url=$2
  [[ -f "$HOME/.config/kitty/$theme.conf" ]] || {
    echo obtaining kitty theme from url
    (
      set -x;
      curl --fail "$curl_url" > "$HOME/.config/kitty/$theme.conf";
    )
  }
}
function obtain_kitty_theme_from_kitten() {
  local theme=$1
  [[ -f "$HOME/.config/kitty/$theme.conf" ]] || {
    echo obtaining kitty theme from kitten
    kitty +kitten themes --dump-theme "$theme" > "$HOME/.config/kitty/$theme.conf"
  }
}
function obtain_kitty_theme_from_github() {
  local theme=$1
  [[ -f "$HOME/.config/kitty/$theme.conf" ]] || {
    echo obtaining kitty theme from github/projekt0n/github-nvim-theme;
    curl --fail https://raw.githubusercontent.com/projekt0n/github-theme-contrib/main/themes/kitty/"$theme".conf > ~/.config/kitty/"$theme".conf;
  }
}

theme=$1
if [[ -z "$theme" ]]; then
  themes=(
    "Apprentice Dark"
    "Ayu Dark"
    "Ayu Light"
    "Ayu Mirage"
    "Catppuccin Frappe"
    "Catppuccin Latte"
    "Catppuccin Macchiato"
    "Catppuccin Mocha"
    "GitHub Dark"
    "GitHub Dark Colorblind"
    "GitHub Dark High Contrast"
    "GitHub Dark Dimmed"
    "GitHub Light"
    "GitHub Light High Contrast"
    "Gruvbox Dark"
    "Gruvbox Light"
    "JetBrains Darcula (dark)"
    "Kanagawa Dragon (dark)"
    "Kanagawa Lotus (light)"
    "Kanagawa Wave (dark)"
    "Neofusion (dark)"
    "Nightfox Nightfox"
    "Nightfox Carbonfox"
    "Nightfox Dayfox"
    "Nightfox Dawnfox"
    "Nightfox Duskfox"
    "Nightfox Nordfox"
    "Nightfox Terafox"
    "One Dark"
    "One Light"
    "Rose Pine"
    "Rose Pine Dawn"
    # "Rose Pine Moon"
    "Seoul256 Dark"
    "Seoul256 Light"
    "TokyoNight Night"
    "TokyoNight Day"
    "TokyoNight Moon"
    "TokyoNight Storm"
    "Zenbones Dark"
    "Zenbones Light"
    "Zenbones Neobones Dark"
    "Zenbones Neobones Light"
    "Zenbones Seoulbones Dark"
    "Zenbones Seoulbones Light"
    "Zenbones Zenwritten Dark"
    "Zenbones Zenwritten Light"
  );
  PS3=$'\n'"select theme> "
  if command -v fzf &> /dev/null; then
    theme=$(( IFS=$'\n'; echo "${themes[*]}" ) | fzf --border=rounded --prompt='Choose a Theme: ')
  else
    select theme in "${themes[@]}"; do
      break
    done
  fi
fi

case $theme in
  "Apprentice Dark")
    obtain_neovim_theme_from_git   Apprentice git@github.com:romainl/Apprentice.git
    change_vim_background          dark
    change_vim_colorscheme         apprentice
    obtain_kitty_theme_from_kitten Apprentice
    change_kitty_theme             Apprentice
    ;;
  "Ayu Dark")
    obtain_neovim_theme_from_git   ayu-vim git@github.com:ayu-theme/ayu-vim.git
    change_vim_background          dark
    change_vim_colorscheme         ayu
    obtain_kitty_theme_from_kitten Ayu
    change_kitty_theme             Ayu
    ;;
  "Ayu Light")
    obtain_neovim_theme_from_git   ayu-vim git@github.com:ayu-theme/ayu-vim.git
    change_vim_background          light
    change_vim_colorscheme         ayu 'ayucolor=light'
    obtain_kitty_theme_from_kitten 'Ayu Light'
    change_kitty_theme             'Ayu Light'
    ;;
  "Ayu Mirage")
    obtain_neovim_theme_from_git   ayu-vim git@github.com:ayu-theme/ayu-vim.git
    change_vim_background          dark
    change_vim_colorscheme         ayu 'ayucolor=mirage'
    obtain_kitty_theme_from_kitten 'Ayu Mirage'
    change_kitty_theme             'Ayu Mirage'
    ;;
  "Catppuccin Frappe")
    obtain_neovim_theme_from_git catppuccin https://github.com/catppuccin/nvim.git
    change_vim_background        dark
    change_vim_colorscheme       catppuccin 'catppuccin_flavour=frappe'
    obtain_kitty_theme_from_curl catppuccin_frappe https://raw.githubusercontent.com/catppuccin/kitty/main/themes/frappe.conf
    change_kitty_theme           catppuccin_frappe
    ;;
  "Catppuccin Latte")
    obtain_neovim_theme_from_git catppuccin https://github.com/catppuccin/nvim.git
    change_vim_background        light
    change_vim_colorscheme       catppuccin 'catppuccin_flavour=latte'
    obtain_kitty_theme_from_curl catppuccin_latte https://raw.githubusercontent.com/catppuccin/kitty/main/themes/latte.conf
    change_kitty_theme           catppuccin_latte
    ;;
  "Catppuccin Macchiato")
    obtain_neovim_theme_from_git catppuccin https://github.com/catppuccin/nvim.git
    change_vim_background        dark
    change_vim_colorscheme       catppuccin 'catppuccin_flavour=macchiato'
    obtain_kitty_theme_from_curl catppuccin_macchiato https://raw.githubusercontent.com/catppuccin/kitty/main/themes/macchiato.conf
    change_kitty_theme           catppuccin_macchiato
    ;;
  "Catppuccin Mocha")
    obtain_neovim_theme_from_git catppuccin https://github.com/catppuccin/nvim.git
    change_vim_background        dark
    change_vim_colorscheme       catppuccin 'catppuccin_flavour=mocha'
    obtain_kitty_theme_from_curl catppuccin_mocha https://raw.githubusercontent.com/catppuccin/kitty/main/themes/mocha.conf
    change_kitty_theme           catppuccin_mocha
    ;;
  "GitHub Dark")
    obtain_neovim_theme_from_git   github-nvim-theme git@github.com:projekt0n/github-nvim-theme.git
    change_vim_background          dark
    change_vim_colorscheme         github_dark
    obtain_kitty_theme_from_github github_dark
    change_kitty_theme             github_dark
    ;;
  "GitHub Dark High Contrast")
    obtain_neovim_theme_from_git   github-nvim-theme git@github.com:projekt0n/github-nvim-theme.git
    change_vim_background          dark
    change_vim_colorscheme         github_dark_high_contrast 
    obtain_kitty_theme_from_github github_dark_high_contrast 
    change_kitty_theme             github_dark_high_contrast 
    ;;
  "GitHub Dark Colorblind")
    obtain_neovim_theme_from_git   github-nvim-theme git@github.com:projekt0n/github-nvim-theme.git
    change_vim_background          dark
    change_vim_colorscheme         github_dark_colorblind
    obtain_kitty_theme_from_github github_dark_colorblind
    change_kitty_theme             github_dark_colorblind
    ;;
  "GitHub Dark Dimmed")
    obtain_neovim_theme_from_git   github-nvim-theme git@github.com:projekt0n/github-nvim-theme.git
    change_vim_background          dark
    change_vim_colorscheme         github_dark_dimmed
    obtain_kitty_theme_from_github github_dark_dimmed
    change_kitty_theme             github_dark_dimmed
    ;;
  "GitHub Light")
    obtain_neovim_theme_from_git   github-nvim-theme git@github.com:projekt0n/github-nvim-theme.git
    change_vim_background          dark
    change_vim_colorscheme         github_light
    obtain_kitty_theme_from_github github_light
    change_kitty_theme             github_light
    ;;
  "GitHub Light High Contrast")
    obtain_neovim_theme_from_git   github-nvim-theme git@github.com:projekt0n/github-nvim-theme.git
    change_vim_background          dark
    change_vim_colorscheme         github_light_high_contrast
    obtain_kitty_theme_from_github github_light_high_contrast
    change_kitty_theme             github_light_high_contrast
    ;;
  "Gruvbox Dark")
    obtain_neovim_theme_from_git   gruvbox git@github.com:morhetz/gruvbox.git
    change_vim_background          dark
    change_vim_colorscheme         gruvbox
    obtain_kitty_theme_from_kitten 'Gruvbox Dark Hard'
    change_kitty_theme             'Gruvbox Dark Hard'
    ;;
  "Gruvbox Light")
    obtain_neovim_theme_from_git   gruvbox git@github.com:morhetz/gruvbox.git
    change_vim_background          light
    change_vim_colorscheme         gruvbox
    obtain_kitty_theme_from_kitten 'Gruvbox Light Hard'
    change_kitty_theme             'Gruvbox Light Hard'
    ;;
  "JetBrains Darcula (dark)")
    obtain_neovim_theme_from_git   darcula-solid git@github.com:santos-gabriel-dario/darcula-solid.nvim.git
    change_vim_background          dark
    change_vim_colorscheme         darcula-solid
    obtain_kitty_theme_from_kitten 'Jet Brains Darcula'
    change_kitty_theme             'Jet Brains Darcula'
    ;;
  "Kanagawa Dragon (dark)")
    obtain_neovim_theme_from_git kanagawa.nvim git@github.com:rebelot/kanagawa.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       kanagawa-dragon
    obtain_kitty_theme_from_curl 'Kanagawa Dragon' https://raw.githubusercontent.com/rebelot/kanagawa.nvim/master/extras/kanagawa_dragon.conf
    change_kitty_theme           'Kanagawa Dragon'
    ;;
  "Kanagawa Lotus (light)")
    obtain_neovim_theme_from_git kanagawa.nvim git@github.com:rebelot/kanagawa.nvim.git
    change_vim_background        light
    change_vim_colorscheme       kanagawa-lotus
    obtain_kitty_theme_from_curl 'Kanagawa Lotus' https://raw.githubusercontent.com/rebelot/kanagawa.nvim/master/extras/kanagawa_light.conf
    change_kitty_theme           'Kanagawa Lotus'
    ;;
  "Kanagawa Wave (dark)")
    obtain_neovim_theme_from_git kanagawa.nvim git@github.com:rebelot/kanagawa.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       kanagawa-wave
    obtain_kitty_theme_from_curl 'Kanagawa Wave' https://raw.githubusercontent.com/rebelot/kanagawa.nvim/master/extras/kanagawa.conf
    change_kitty_theme           'Kanagawa Wave'
    ;;
  "Neofusion (dark)")
    obtain_neovim_theme_from_git neofusion.nvim https://github.com/diegoulloao/neofusion.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       neofusion
    obtain_kitty_theme_from_curl 'neofusion-dark' https://raw.githubusercontent.com/diegoulloao/neofusion.kitty/main/neofusion.conf
    change_kitty_theme           'neofusion-dark'
    ;;
  "Nightfox Nightfox")
    obtain_neovim_theme_from_git nightfox.nvim git@github.com:EdenEast/nightfox.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       nightfox
    obtain_kitty_theme_from_curl 'nightfox-nightfox' https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/nightfox/nightfox_kitty.conf
    change_kitty_theme           'nightfox-nightfox'
    ;;
  "Nightfox Carbonfox")
    obtain_neovim_theme_from_git nightfox.nvim git@github.com:EdenEast/nightfox.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       carbonfox
    obtain_kitty_theme_from_curl 'nightfox-carbonfox' https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/carbonfox/nightfox_kitty.conf
    change_kitty_theme           'nightfox-carbonfox'
    ;;
  "Nightfox Dayfox")
    obtain_neovim_theme_from_git nightfox.nvim git@github.com:EdenEast/nightfox.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       dayfox
    obtain_kitty_theme_from_curl 'nightfox-dayfox' https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/dayfox/nightfox_kitty.conf
    change_kitty_theme           'nightfox-dayfox'
    ;;
  "Nightfox Dawnfox")
    obtain_neovim_theme_from_git nightfox.nvim git@github.com:EdenEast/nightfox.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       dawnfox
    obtain_kitty_theme_from_curl 'nightfox-dawnfox' https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/dawnfox/nightfox_kitty.conf
    change_kitty_theme           'nightfox-dawnfox'
    ;;
  "Nightfox Duskfox")
    obtain_neovim_theme_from_git nightfox.nvim git@github.com:EdenEast/nightfox.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       duskfox
    obtain_kitty_theme_from_curl 'nightfox-duskfox' https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/duskfox/nightfox_kitty.conf
    change_kitty_theme           'nightfox-duskfox'
    ;;
  "Nightfox Nordfox")
    obtain_neovim_theme_from_git nightfox.nvim git@github.com:EdenEast/nightfox.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       nordfox
    obtain_kitty_theme_from_curl 'nightfox-nordfox' https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/nordfox/nightfox_kitty.conf
    change_kitty_theme           'nightfox-nordfox'
    ;;
  "Nightfox Terafox")
    obtain_neovim_theme_from_git nightfox.nvim git@github.com:EdenEast/nightfox.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       terafox
    obtain_kitty_theme_from_curl 'nightfox-terafox' https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/terafox/nightfox_kitty.conf
    change_kitty_theme           'nightfox-terafox'
    ;;
  "One Dark")
    obtain_neovim_theme_from_git   onedark.vim git@github.com:joshdick/onedark.vim.git
    change_vim_background          dark
    change_vim_colorscheme         onedark
    obtain_kitty_theme_from_kitten 'One Dark'
    change_kitty_theme             'One Dark'
    ;;
  "One Light")
    obtain_neovim_theme_from_git   vim-one git@github.com:rakr/vim-one.git
    change_vim_background          light
    change_vim_colorscheme         one
    obtain_kitty_theme_from_kitten 'One Half Light'
    change_kitty_theme             'One Half Light'
    ;;
  "Rose Pine")
    obtain_neovim_theme_from_git   rose-pine git@github.com:rose-pine/neovim.git
    change_vim_background          dark
    change_vim_colorscheme         rose-pine
    obtain_kitty_theme_from_curl   'Rose Pine' https://raw.githubusercontent.com/rose-pine/kitty/main/dist/rose-pine.conf
    change_kitty_theme             'Rose Pine'
    ;;
  "Rose Pine Dawn")
    obtain_neovim_theme_from_git   rose-pine git@github.com:rose-pine/neovim.git
    change_vim_background          light
    change_vim_colorscheme         rose-pine
    obtain_kitty_theme_from_curl   'Rose Pine Dawn' https://raw.githubusercontent.com/rose-pine/kitty/main/dist/rose-pine-dawn.conf
    change_kitty_theme             'Rose Pine Dawn'
    ;;
  # "Rose Pine Moon")
  #   obtain_neovim_theme_from_git   rose-pine git@github.com:rose-pine/neovim.git
  #   change_vim_background          dark 'dark_variant=moon'
  #   change_vim_colorscheme         rose-pine
  #   obtain_kitty_theme_from_curl   'Rose Pine Moon' https://raw.githubusercontent.com/rose-pine/kitty/main/dist/rose-pine-moon.conf
  #   change_kitty_theme             'Rose Pine Moon'
  #   ;;
  "Seoul256 Dark")
    obtain_neovim_theme_from_git seoul256.vim git@github.com:junegunn/seoul256.vim.git
    change_vim_background        dark
    change_vim_colorscheme       seoul256
    obtain_kitty_theme_from_curl seoul256 https://raw.githubusercontent.com/malikbenkirane/kitty-colors/master/seoul256.kitty-conf
    change_kitty_theme           seoul256
    ;;
  "Seoul256 Light")
    obtain_neovim_theme_from_git seoul256.vim git@github.com:junegunn/seoul256.vim.git
    change_vim_background        light
    change_vim_colorscheme       seoul256-light
    obtain_kitty_theme_from_curl seoul256-light https://raw.githubusercontent.com/malikbenkirane/kitty-colors/master/seoul256-light.kitty-conf
    change_kitty_theme           seoul256-light
    ;;
  "TokyoNight Night")
    obtain_neovim_theme_from_git   tokyonight.nvim git@github.com:folke/tokyonight.nvim.git
    change_vim_background          dark
    change_vim_colorscheme         tokyonight-night
    obtain_kitty_theme_from_kitten "Tokyo Night"
    change_kitty_theme             "Tokyo Night"
    ;;
  "TokyoNight Day")
    obtain_neovim_theme_from_git   tokyonight.nvim git@github.com:folke/tokyonight.nvim.git
    change_vim_background          light
    change_vim_colorscheme         tokyonight-day
    obtain_kitty_theme_from_kitten "Tokyo Night Day"
    change_kitty_theme             "Tokyo Night Day"
    ;;
  "TokyoNight Moon")
    obtain_neovim_theme_from_git   tokyonight.nvim git@github.com:folke/tokyonight.nvim.git
    change_vim_background          dark
    change_vim_colorscheme         tokyonight-moon
    obtain_kitty_theme_from_kitten "Tokyo Night Storm"
    change_kitty_theme             "Tokyo Night Storm"
    ;;
  "TokyoNight Storm")
    obtain_neovim_theme_from_git   tokyonight.nvim git@github.com:folke/tokyonight.nvim.git
    change_vim_background          dark
    change_vim_colorscheme         tokyonight-storm
    obtain_kitty_theme_from_kitten "Tokyo Night Moon"
    change_kitty_theme             "Tokyo Night Moon"
    ;;
  "Zenbones Dark")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       zenbones zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-dark https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/zenbones_dark.conf
    change_kitty_theme           zenbones-dark
    ;;
  "Zenbones Light")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        light
    change_vim_colorscheme       zenbones zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-light https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/zenbones_light.conf
    change_kitty_theme           zenbones-light
    ;;
  "Zenbones Zenwritten Dark")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       zenwritten zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-zenwritten-dark https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/zenwritten_dark.conf
    change_kitty_theme           zenbones-zenwritten-dark
    echo TODO: zenbones requires the \'lush\' lua rock \(can be installed manually\)
    ;;
  "Zenbones Zenwritten Light")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        light
    change_vim_colorscheme       zenwritten zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-zenwritten-light https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/zenwritten_light.conf
    change_kitty_theme           zenbones-zenwritten-light
    echo TODO: zenbones requires the \'lush\' lua rock \(can be installed manually\)
    ;;
  "Zenbones Neobones Light")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        light
    change_vim_colorscheme       neobones zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-neobones-light https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/neobones_light.conf
    change_kitty_theme           zenbones-neobones-light
    echo TODO: zenbones requires the \'lush\' lua rock \(can be installed manually\)
    ;;
  "Zenbones Neobones Dark")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       neobones zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-neobones-dark https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/neobones_dark.conf
    change_kitty_theme           zenbones-neobones-dark
    echo TODO: zenbones requires the \'lush\' lua rock \(can be installed manually\)
    ;;
  "Zenbones Seoulbones Light")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        light
    change_vim_colorscheme       seoulbones zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-seoulbones-light https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/seoulbones_light.conf
    change_kitty_theme           zenbones-seoulbones-light
    echo TODO: zenbones requires the \'lush\' lua rock \(can be installed manually\)
    ;;
  "Zenbones Seoulbones Dark")
    obtain_neovim_theme_from_git zenbones.nvim git@github.com:mcchrish/zenbones.nvim.git
    change_vim_background        dark
    change_vim_colorscheme       seoulbones zenbones_compat=1
    obtain_kitty_theme_from_curl zenbones-seoulbones-dark https://raw.githubusercontent.com/mcchrish/zenbones.nvim/main/extras/kitty/seoulbones_dark.conf
    change_kitty_theme           zenbones-seoulbones-dark
    echo TODO: zenbones requires the \'lush\' lua rock \(can be installed manually\)
    ;;
  *)
    echo "\"$theme\" is not a recognized theme"
    ;;
esac
if [[ -n "$KITTY_PID" ]]; then
  kill -SIGUSR1 "$KITTY_PID"
fi
